// examples/vue/src/App.vue
<script setup lang="ts">
import { DotLottieComponent, useDotLottieControls } from '@lottiepro-web/dotlottie-vue';
import { onMounted } from 'vue';

const lottieRef = useDotLottieControls();

const handleLoad = () => {
  console.log('Animation loaded!');
};

const handleError = (error: Error) => {
  console.error('Failed to load animation:', error);
};
</script>

<template>
  <div class="container">
    <DotLottieComponent
      ref="lottieRef"
      src="https://res.cloudinary.com/anaskhan/raw/upload/v1749145365/lottiepro/volcano_mmfo32.lottie"
      :style="{ width: '400px', height: '400px' }"
      :loop="true"
      :autoplay="true"
      @load="handleLoad"
      @error="handleError"
    />

    <div class="controls">
      <button @click="lottieRef.value?.play()">Play</button>
      <button @click="lottieRef.value?.pause()">Pause</button>
      <button @click="lottieRef.value?.stop()">Stop</button>
      <button @click="lottieRef.value?.setSpeed(0.5)">Slow Motion</button>
      <button @click="lottieRef.value?.setSpeed(2)">Fast Forward</button>
      <button @click="lottieRef.value?.setDirection(-1)">Reverse</button>
    </div>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 2rem;
  gap: 1rem;
}

.controls {
  display: flex;
  gap: 0.5rem;
}

button {
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 4px;
  background-color: #646cff;
  color: white;
  cursor: pointer;
  transition: background-color 0.2s;
}

button:hover {
  background-color: #535bf2;
}
</style>

// examples/next/app/page.tsx
'use client'
import Image from "next/image";
import { DotLottieComponent, useDotLottieControls } from '@lottiepro-web/dotlottie-react';

export default function Home() {
  const lottieRef = useDotLottieControls();

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-b from-gray-50 to-gray-100 px-4 py-8">
      <div className="bg-white rounded-lg shadow-xl p-6 max-w-lg w-full">
        <h1 className="text-2xl font-bold text-center mb-6 text-gray-800">LottiePro Player</h1>
        
        <div className="flex justify-center mb-8">
          <DotLottieComponent
            ref={lottieRef}
            src="https://res.cloudinary.com/anaskhan/raw/upload/v1749145365/lottiepro/volcano_mmfo32.lottie"
            style={{ width: 400, height: 400 }}
            loop={true}
            onLoad={() => console.log('Animation loaded')}
            onError={(error) => console.error('Failed to load animation:', error)}
          />
        </div>

        <div className="grid grid-cols-3 gap-3">
          <button 
            onClick={() => lottieRef.current?.play()}
            className="bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 transition duration-200 font-medium"
          >
            Play
          </button>
          <button 
            onClick={() => lottieRef.current?.pause()}
            className="bg-amber-500 text-white py-2 px-4 rounded-md hover:bg-amber-600 transition duration-200 font-medium"
          >
            Pause
          </button>
          <button 
            onClick={() => lottieRef.current?.stop()}
            className="bg-red-500 text-white py-2 px-4 rounded-md hover:bg-red-600 transition duration-200 font-medium"
          >
            Stop
          </button>
          <button 
            onClick={() => lottieRef.current?.setSpeed(0.5)}
            className="bg-teal-500 text-white py-2 px-4 rounded-md hover:bg-teal-600 transition duration-200 font-medium"
          >
            Slow
          </button>
          <button 
            onClick={() => lottieRef.current?.setSpeed(2)}
            className="bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 transition duration-200 font-medium"
          >
            Fast
          </button>
          <button 
            onClick={() => lottieRef.current?.setDirection(-1)}
            className="bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 transition duration-200 font-medium"
          >
            Reverse
          </button>
        </div>
      </div>
    </div>
  );
}
